# Generated by Django 3.2.8 on 2021-10-13 02:21

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evolution",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("specie_id", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Specie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evolves_from", models.CharField(max_length=4, null=True)),
                ("evolves_to", models.CharField(max_length=4, null=True)),
                (
                    "evolution_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokeapi.evolution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                (
                    "specie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokeapi.specie",
                    ),
                ),
            ],
        ),
    ]
